rm(list = ls())

library(data.table)
## Directories and file paths

## CODE DIRECTORY
## Update with location of directory where code folder "external publications" if saved.
user_repo <-  "/path/to/code/directory/"


## INPUT DATA
## Data can be downloaded here 
##   https://vizhub.healthdata.org/gbd-results?params=gbd-api-2021-permalink/898b96e8fdf5dd9ee7476b58e84066ba
## Path to sample data
df <- fread(paste0(user_repo, '/external_publications/Figures/Arrow_diagram/inputs/sample_data.csv'))
## OR
## Update with path to your input data
#df <- fread("path/to/input/data.csv")

## Inputs and Hierarchies
## Path to input data generated by this code for final figure
## Update as needed
## !! If you change this, you will need to update it in line 19 of arrow_chart_gen.py as well!!
output_filepath <- paste0(user_repo, 'external_publications/Figures/Arrow_diagram/inputs/arrow_prep.csv')
print(paste("Arrow diagram data being saved to", output_filepath))

## Cause hierarchy
## Update as needed
## !! if you change this, you will need to update it in line 14 of arrow_chart_gen.py as well!!
causes_filepath <- paste0(user_repo, "external_publications/hierarchies/cause_GBD2021.csv")
print(paste("using", causes_filepath, "for cause hierarchy..."))

## Years for 3 columns in arrow diagram
year1 <- 1990
year2 <- 2000
year3 <- 2021

## ---------------------------------------------------------------------------------------------------------

## Run code to prep data and create arrow diagram:
source("arrow_data_prep.R")
